# Generated by Django 4.0.2 on 2022-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_edicion',
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
